CREATE  DATABASE WPI;
USE wpi;

DESCRIBE wpi_data_food;

ALTER TABLE wpi_data_food
DROP COLUMN `(G). MANUFACTURE OF WOOD AND OF PRODUCTS OF WOOD AND CORK`;

ALTER TABLE wpi_data_food
DROP COLUMN `(L). MANUFACTURE OF RUBBER AND PLASTICS PRODUCTS`;

ALTER TABLE wpi_data_food
DROP COLUMN `(M). MANUFACTURE OF OTHER NON-METALLIC MINERAL PRODUCTS`;

ALTER TABLE wpi_data_food
DROP COLUMN `(N). MANUFACTURE OF BASIC METALS`;

ALTER TABLE wpi_data_food
DROP COLUMN `(S). MANUFACTURE OF MOTOR VEHICLES, TRAILERS AND SEMI-TRAILERS`;

ALTER TABLE wpi_data_food RENAME COLUMN `ï»¿mom_id` TO mom_id;

SELECT * FROM wpi_data_food;